-- MySQL Script generated by MySQL Workbench
-- Tue Mar 14 14:23:57 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genero` (
  `ID_Genero` INT NOT NULL AUTO_INCREMENT,
  `Genero` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clasificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clasificacion` (
  `ID_Clasificacion` INT NOT NULL AUTO_INCREMENT,
  `Clasificacion` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Clasificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peliculas` (
  `ID_Peliculas` INT NOT NULL AUTO_INCREMENT,
  `Titulo_Peliculas` VARCHAR(45) NULL,
  `Genero_ID_Genero` INT NOT NULL,
  `Director_Peliculas` VARCHAR(45) NULL,
  `Duracion_Peliculas` INT NULL,
  `Anio_Peliculas` INT NULL,
  `Sub_Peliculas` TINYINT(1) NULL,
  `Clasificacion_ID_Clasificacion` INT NOT NULL,
  `Sinopsis_Peliculas` VARCHAR(100) NULL,
  `Foto_Peliculas` BLOB NULL,
  `Cast_Peliculas` VARCHAR(45) NULL,
  `Votos_Peliculas` INT NULL,
  PRIMARY KEY (`ID_Peliculas`, `Genero_ID_Genero`, `Clasificacion_ID_Clasificacion`),
  INDEX `fk_Peliculas_Genero1_idx` (`Genero_ID_Genero` ASC),
  INDEX `fk_Peliculas_Clasificacion1_idx` (`Clasificacion_ID_Clasificacion` ASC),
  CONSTRAINT `fk_Peliculas_Genero1`
    FOREIGN KEY (`Genero_ID_Genero`)
    REFERENCES `mydb`.`Genero` (`ID_Genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peliculas_Clasificacion1`
    FOREIGN KEY (`Clasificacion_ID_Clasificacion`)
    REFERENCES `mydb`.`Clasificacion` (`ID_Clasificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Horario` (
  `ID_Horario` INT NOT NULL AUTO_INCREMENT,
  `Horario` VARCHAR(10) NULL,
  PRIMARY KEY (`ID_Horario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funciones` (
  `ID_Funciones` INT NOT NULL AUTO_INCREMENT,
  `Peliculas_ID_Peliculas` INT NOT NULL,
  `Salas_Funciones` VARCHAR(3) NULL,
  `Horario_ID_Horario` INT NOT NULL,
  PRIMARY KEY (`ID_Funciones`, `Peliculas_ID_Peliculas`, `Horario_ID_Horario`),
  INDEX `fk_Funciones_Horario1_idx` (`Horario_ID_Horario` ASC),
  INDEX `fk_Funciones_Peliculas1_idx` (`Peliculas_ID_Peliculas` ASC),
  CONSTRAINT `fk_Funciones_Horario1`
    FOREIGN KEY (`Horario_ID_Horario`)
    REFERENCES `mydb`.`Horario` (`ID_Horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funciones_Peliculas1`
    FOREIGN KEY (`Peliculas_ID_Peliculas`)
    REFERENCES `mydb`.`Peliculas` (`ID_Peliculas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservaciones` (
  `ID_Reservacion` VARCHAR(10) NOT NULL,
  `Asientos_Reservacion` VARCHAR(3) NULL,
  `Funciones_ID_Funciones` INT NOT NULL,
  PRIMARY KEY (`ID_Reservacion`, `Funciones_ID_Funciones`),
  INDEX `fk_Reservaciones_Funciones1_idx` (`Funciones_ID_Funciones` ASC),
  CONSTRAINT `fk_Reservaciones_Funciones1`
    FOREIGN KEY (`Funciones_ID_Funciones`)
    REFERENCES `mydb`.`Funciones` (`ID_Funciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Miembros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Miembros` (
  `ID_Miembro` VARCHAR(45) NOT NULL,
  `Nombre_Miembro` VARCHAR(45) NULL,
  `A.Pat_Miembro` VARCHAR(45) NULL,
  `A.Mat_Miembro` VARCHAR(45) NULL,
  `Contra_Miembro` VARCHAR(45) NULL,
  `Reservaciones_ID_Reservacion` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID_Miembro`, `Reservaciones_ID_Reservacion`),
  INDEX `fk_Miembros_Reservaciones1_idx` (`Reservaciones_ID_Reservacion` ASC),
  CONSTRAINT `fk_Miembros_Reservaciones1`
    FOREIGN KEY (`Reservaciones_ID_Reservacion`)
    REFERENCES `mydb`.`Reservaciones` (`ID_Reservacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Precios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Precios` (
  `ID_Precio` INT NOT NULL,
  `Precio` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Precio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administradores` (
  `ID_Administrador` VARCHAR(45) NOT NULL,
  `Nombre_Administrador` VARCHAR(45) NULL,
  `A.Pat_Administrador` VARCHAR(45) NULL,
  `A.Mat_Administrador` VARCHAR(45) NULL,
  `Contra_Administrador` VARCHAR(45) NULL,
  `Tipo_Administrador` INT(2) NULL,
  PRIMARY KEY (`ID_Administrador`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
